#!/usr/bin/env bun
// gen-registry — auto-discover the film registry.
//
// Scans films/*.json and writes src/engine/films.generated.ts: a module of
// STATIC `import` lines plus the `FILMS` record literal. Static imports are
// deliberate — Remotion's bundler must see every spec at build time, so the
// engine never does a runtime fs glob. Adding a film is now one JSON file;
// re-run this script (it is idempotent) and the registry catches up.
//
//   bun cli/gen-registry.ts

import {readdirSync, writeFileSync, readFileSync} from 'node:fs';
import {join, relative} from 'node:path';
import {ENGINE_ROOT, paths} from './paths';

const OUT = join(ENGINE_ROOT, 'src', 'engine', 'films.generated.ts');

// A safe TS identifier for a film id (e.g. "kubernetes-pr" -> "kubernetesPr").
const ident = (id: string): string =>
  id.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) =>
    c ? c.toUpperCase() : '',
  );

const main = (): void => {
  // Sorted for a deterministic, idempotent output.
  const ids = readdirSync(paths.films)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort();

  if (ids.length === 0) throw new Error(`no films found in ${paths.films}`);

  // Import paths are relative to the generated module's own directory, posix
  // style so the source is identical on every platform.
  const fromDir = join(ENGINE_ROOT, 'src', 'engine');
  const importPath = (id: string): string => {
    const rel = relative(fromDir, join(paths.films, `${id}.json`));
    return (rel.startsWith('.') ? rel : `./${rel}`).split(/[\\/]/).join('/');
  };

  // Guard against an id whose identifier collides with another's.
  const seen = new Map<string, string>();
  for (const id of ids) {
    const key = ident(id);
    const prev = seen.get(key);
    if (prev) throw new Error(`film ids "${prev}" and "${id}" map to the same identifier "${key}"`);
    seen.set(key, id);
  }

  const imports = ids
    .map((id) => `import ${ident(id)} from '${importPath(id)}';`)
    .join('\n');
  const entries = ids
    .map((id) => `  '${id}': ${ident(id)} as FilmSpec,`)
    .join('\n');

  const body = `// AUTO-GENERATED by cli/gen-registry.ts — do not edit by hand.
// Regenerate with:  bun cli/gen-registry.ts
//
// The film registry, discovered by scanning films/*.json. Static imports are
// required so Remotion's bundler can see every spec at build time.

import type {FilmSpec} from './spec';

${imports}

export const FILMS: Record<string, FilmSpec> = {
${entries}
};
`;

  // Idempotent: skip the write (and its mtime bump) when nothing changed.
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* file does not exist yet */
  }
  if (current === body) {
    console.log(`films.generated.ts already current — ${ids.length} film(s).`);
    return;
  }
  writeFileSync(OUT, body);
  console.log(`wrote ${relative(ENGINE_ROOT, OUT)} — ${ids.length} film(s): ${ids.join(', ')}`);
};

main();
