// AUTO-GENERATED by scripts/gen-manifest.ts. Do NOT edit by hand.
//
// Regenerate after adding/removing/renaming a plugin directory:
//   bun packages/core/scripts/gen-manifest.ts
//
// The generator globs src/{scenes,presets,features,tts}/*/index.{ts,tsx} and
// emits the convention-named named export for each (see scripts/gen-manifest.ts
// for the convention and the override mechanism). The order below is the
// canonical plugin-load order — see CATEGORIES in the generator for the
// per-category ordering rules.
//
// Total plugins: 39

import type {Plugin} from '@bjelser/kit';


// Presets (6)
import {neutralPreset} from './presets/neutral';
import {engineeringPreset} from './presets/engineering';
import {editorialPreset} from './presets/editorial';
import {paperPreset} from './presets/paper';
import {analyticalPreset} from './presets/analytical';
import {executivePreset} from './presets/executive';

// Features (3)
import {narrationFeature} from './features/narration';
import {audioRhythmFeature} from './features/audio-rhythm';
import {audioBedFeature} from './features/audio-bed';

// TTS providers (1)
import {kokoroTtsPlugin} from './tts/kokoro';

// Translation providers (1)
import {noopTranslationPlugin} from './translation/noop';

// Scenes (29)
import {bigIdeaPlugin} from './scenes/big-idea';
import {causalLoopPlugin} from './scenes/causal-loop';
import {chartPlugin} from './scenes/chart';
import {closeupPlugin} from './scenes/closeup';
import {comparePlugin} from './scenes/compare';
import {concessionPlugin} from './scenes/concession';
import {demonstratePlugin} from './scenes/demonstrate';
import {diffPlugin} from './scenes/diff';
import {epigraphPlugin} from './scenes/epigraph';
import {figurePlugin} from './scenes/figure';
import {framePlugin} from './scenes/frame';
import {journeyMapPlugin} from './scenes/journey-map';
import {landscapePlugin} from './scenes/landscape';
import {mapPlugin} from './scenes/map';
import {mechanismPlugin} from './scenes/mechanism';
import {objectionPlugin} from './scenes/objection';
import {passagePlugin} from './scenes/passage';
import {priorArtPlugin} from './scenes/prior-art';
import {probePlugin} from './scenes/probe';
import {progressionPlugin} from './scenes/progression';
import {provocationPlugin} from './scenes/provocation';
import {quantitiesPlugin} from './scenes/quantities';
import {recapPlugin} from './scenes/recap';
import {structurePlugin} from './scenes/structure';
import {tensionPlugin} from './scenes/tension';
import {timelinePlugin} from './scenes/timeline';
import {treePlugin} from './scenes/tree';
import {vennPlugin} from './scenes/venn';
import {walkthroughPlugin} from './scenes/walkthrough';

// Named re-exports for callers that want them directly.
// Presets
export {neutralPreset, engineeringPreset, editorialPreset, paperPreset, analyticalPreset, executivePreset};

// Features
export {narrationFeature, audioRhythmFeature, audioBedFeature};

// TTS providers
export {kokoroTtsPlugin};

// Translation providers
export {noopTranslationPlugin};

// Scenes
export {bigIdeaPlugin, causalLoopPlugin, chartPlugin, closeupPlugin, comparePlugin, concessionPlugin, demonstratePlugin, diffPlugin, epigraphPlugin, figurePlugin, framePlugin, journeyMapPlugin, landscapePlugin, mapPlugin, mechanismPlugin, objectionPlugin, passagePlugin, priorArtPlugin, probePlugin, progressionPlugin, provocationPlugin, quantitiesPlugin, recapPlugin, structurePlugin, tensionPlugin, timelinePlugin, treePlugin, vennPlugin, walkthroughPlugin};

/**
 * The set of plugins shipped with `@bjelser/core` — the opinionated default
 * implementation. The engine's `use()` sniffs `plugin.kind` and dispatches
 * to the right registry, so loading order is irrelevant to correctness; the
 * order below is stable for reviewability (presets first, then features, TTS,
 * then scenes alphabetically).
 */
export const corePlugins: readonly Plugin[] = [
  // Presets (6)
  neutralPreset,
  engineeringPreset,
  editorialPreset,
  paperPreset,
  analyticalPreset,
  executivePreset,
  // Features (3)
  narrationFeature,
  audioRhythmFeature,
  audioBedFeature,
  // TTS providers (1)
  kokoroTtsPlugin,
  // Translation providers (1)
  noopTranslationPlugin,
  // Scenes (29)
  bigIdeaPlugin,
  causalLoopPlugin,
  chartPlugin,
  closeupPlugin,
  comparePlugin,
  concessionPlugin,
  demonstratePlugin,
  diffPlugin,
  epigraphPlugin,
  figurePlugin,
  framePlugin,
  journeyMapPlugin,
  landscapePlugin,
  mapPlugin,
  mechanismPlugin,
  objectionPlugin,
  passagePlugin,
  priorArtPlugin,
  probePlugin,
  progressionPlugin,
  provocationPlugin,
  quantitiesPlugin,
  recapPlugin,
  structurePlugin,
  tensionPlugin,
  timelinePlugin,
  treePlugin,
  vennPlugin,
  walkthroughPlugin,
];

export default corePlugins;
