"""Example archcast scene — a generic web-service architecture, narrated.

Render:  uv run manim -qm scenes/example.py ExampleArchitecture

This is a template. A real architecture review is generated by surveying an
actual codebase — see AGENTS.md.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from manim import *  # noqa: F403, E402
from archcast import ArchScene, component, connect, caption  # noqa: E402


class ExampleArchitecture(ArchScene):
    def construct(self):
        title = Text("Example Service — Architecture Review",
                     weight=BOLD, font_size=36)
        title.to_edge(UP, buff=0.5)

        with self.voiceover(text=(
            "Here is the architecture of a small web service, at a glance -- "
            "three layers, each with a single job."
        )):
            self.play(Write(title))

        web = component("Web UI", "what the user sees", color=BLUE)
        api = component("API Server", "answers requests", color=GREEN)
        db = component("Database", "stores the data", color=ORANGE)
        layers = VGroup(web, api, db).arrange(DOWN, buff=1.05)

        with self.voiceover(text=(
            "At the top is the web interface. In the middle, the API server, "
            "which handles every request. At the bottom, the database, where "
            "the data is kept."
        )):
            self.play(LaggedStart(
                FadeIn(web, shift=UP * 0.3),
                FadeIn(api, shift=UP * 0.3),
                FadeIn(db, shift=UP * 0.3),
                lag_ratio=0.6,
            ))

        down1 = connect(web, api)
        down2 = connect(api, db)
        with self.voiceover(text=(
            "Work flows downward. The web interface calls the API; the API "
            "queries the database. Each layer talks only to its neighbour."
        )):
            self.play(GrowArrow(down1))
            self.play(GrowArrow(down2))

        note = caption("a real review is generated by surveying actual code")
        with self.voiceover(text=(
            "This is only a template. A real architecture review is built by "
            "surveying a true codebase, component by component."
        )):
            self.play(FadeIn(note))
        self.wait(0.3)
        self.play(FadeOut(VGroup(title, layers, down1, down2, note)))
