// AUTO-GENERATED by cli/gen-registry.ts — do not edit by hand.
// Regenerate with:  bun cli/gen-registry.ts
//
// The film registry, discovered by scanning films/*.json. Static imports are
// required so Remotion's bundler can see every spec at build time.

import type {FilmSpec} from './spec';

import euclidPrimes from '../../../../films/euclid-primes.json';
import grammarCheck from '../../../../films/grammar-check.json';
import kubernetesPr from '../../../../films/kubernetes-pr.json';
import linearAlgebra from '../../../../films/linear-algebra.json';
import onboardingFirst30Minutes from '../../../../films/onboarding-first-30-minutes.json';
import stoppingByWoods from '../../../../films/stopping-by-woods.json';

export const FILMS: Record<string, FilmSpec> = {
  'euclid-primes': euclidPrimes as FilmSpec,
  'grammar-check': grammarCheck as FilmSpec,
  'kubernetes-pr': kubernetesPr as FilmSpec,
  'linear-algebra': linearAlgebra as FilmSpec,
  'onboarding-first-30-minutes': onboardingFirst30Minutes as FilmSpec,
  'stopping-by-woods': stoppingByWoods as FilmSpec,
};
