// Generator for the per-render Remotion entry script.
//
// Why per-render: Remotion bundles for chromium; everything reachable from
// the entry must be statically importable at bundle time. Plugins live in
// `@docent/core` (always) plus optionally in a user `docent.config.ts`. The
// CLI knows both paths at render time and writes a small entry .tsx that
// statically imports them and calls `registerKitRoot({plugins, spec})`.
//
// Why TS (not pre-compiled JS): Remotion's bundler accepts .tsx and runs
// esbuild/webpack with TS support. The generated entry is throwaway — it
// lives under `<projectRoot>/.docent/tmp/` and is overwritten each render.

import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, relative, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

import type {Plugin} from '@docent/kit';

export interface GenerateEntryOptions {
  /** Absolute path of the film spec JSON. */
  readonly specPath: string;
  /** Absolute path of the user docent.config file (or null). */
  readonly configPath: string | null;
  /** The film id — used in the generated entry filename. */
  readonly filmId: string;
  /** Project root — the entry is written under `<projectRoot>/.docent/tmp/`. */
  readonly projectRoot: string;
  /**
   * The set of user plugins, post-loadConfig. Surfaced for diagnostics; the
   * generator references them by config-file path, not by value.
   */
  readonly userPlugins: ReadonlyArray<Plugin>;
}

/** Resolve the absolute path of a package's package.json `main`. */
const resolvePackageEntry = async (name: string): Promise<string> => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const meta = import.meta as any;
  if (typeof meta.resolve === 'function') {
    try {
      const url = await meta.resolve(name);
      if (typeof url === 'string' && url.startsWith('file:')) {
        return fileURLToPath(url);
      }
    } catch {
      // fall through
    }
  }
  try {
    const req = Function('return require')() as NodeJS.Require;
    return req.resolve(name);
  } catch {
    throw new Error(
      `[@docent/cli] could not resolve "${name}" — is it installed?`,
    );
  }
};

/**
 * Generate a per-render Remotion entry .tsx file under `.docent/tmp/`.
 * Returns the absolute path. The file is overwritten each render and is
 * safe to ignore in source control.
 */
export const generateRenderEntry = async (
  opts: GenerateEntryOptions,
): Promise<string> => {
  const tmpDir = resolve(opts.projectRoot, '.docent', 'tmp');
  mkdirSync(tmpDir, {recursive: true});
  const entryPath = resolve(
    tmpDir,
    `render-entry-${opts.filmId}.${Date.now()}.tsx`,
  );

  // Resolve absolute paths to @docent/kit and @docent/core so the generated
  // entry can import them as filesystem paths. This sidesteps any node-
  // modules resolution surprises inside the tmp dir.
  const kitEntry = await resolvePackageEntry('@docent/kit');
  const coreEntry = await resolvePackageEntry('@docent/core');

  // Compute relative paths from the entry's directory to each target.
  const relSpec = relative(dirname(entryPath), opts.specPath).replace(/\\/g, '/');
  const relCore = relative(dirname(entryPath), coreEntry).replace(/\\/g, '/');
  // For the kit, we want to import the buildKitRoot helper specifically.
  // The kit entry source lives at <kitDir>/remotion/entry.tsx. We use the .tsx
  // extension explicitly so the bundler doesn't fall back to .ts/.js by
  // accident.
  const kitDir = dirname(kitEntry);
  const relKitEntryHelper = relative(
    dirname(entryPath),
    resolve(kitDir, 'remotion', 'entry.tsx'),
  ).replace(/\\/g, '/');

  const prefix = (p: string): string => (p.startsWith('.') ? p : './' + p);

  const userImport = opts.configPath
    ? `import userConfig from ${JSON.stringify(
        prefix(relative(dirname(entryPath), opts.configPath).replace(/\\/g, '/')),
      )};
const userPlugins = Array.isArray(userConfig?.plugins) ? userConfig.plugins : [];`
    : `const userPlugins: any[] = [];`;

  // NOTE: Remotion's CLI greps the entry source for the literal string
  // "registerRoot" (see node_modules/@remotion/bundler/dist/bundle.js
  // validateEntryPoint). We MUST call `registerRoot` by name here (not via a
  // wrapper helper) so the validator finds the marker.
  const source = `// AUTO-GENERATED by @docent/cli — do not edit; regenerated per render.
// Statically imports @docent/core and optional user plugins so webpack can
// bundle every scene component referenced by the film for chromium-side
// frame rendering.
import {registerRoot} from 'remotion';
import {buildKitRoot} from ${JSON.stringify(prefix(relKitEntryHelper))};
import corePlugins from ${JSON.stringify(prefix(relCore))};
import spec from ${JSON.stringify(prefix(relSpec))};
${userImport}

const all = [...corePlugins, ...userPlugins];
registerRoot(buildKitRoot({plugins: all, spec}));
`;
  writeFileSync(entryPath, source, 'utf-8');
  return entryPath;
};
